disable metric attributes
oracle/wookiee pull request #213
Opened 2022-08-29 06:22 UTC by singhalak11

Added a configurable key containing list of metric attributes to be disabled in Graphite reporter.

2022-08-30 14:51 UTC, malibuworkcrew requested changes
Looks great! The only change is let's go to version 2.3.14-- we'll be going to 2.4.x soon for a restructure of how we use cats so I'd prefer to stay at 2.3 for now

2022-08-30 14:58 UTC, Kraagen commented on wookiee-metrics/src/main/scala/com/oracle/infy/wookiee/component/metrics/MetricsActor.scala
> +          settings.GraphiteDisabledMetricAttributes.get.toSet.map(MetricAttribute.valueOf).asJava
We like to avoid calling .get an Option even with a .nonEmpty check before.

Matching on the Option or using a foreach is preferred.

2022-08-30 15:03 UTC, Kraagen commented on wookiee-metrics/src/main/scala/com/oracle/infy/wookiee/component/metrics/monitoring/MonitoringSettings.scala
> +    Try(Option(config.getStringList("graphite.disabled-metric-attributes").asScala.toList)).getOrElse(None)
Try has a toOption on it where it will return Some(...) if it succeeds or None if it doesn't. No need to wrap the Option with Try and then use .getOrElse.

If order is irrelevant and we always convert it to a Set, why don't we just have it be a Set from the beginning?

2022-09-01 09:51 UTC, singhalak11 commented on wookiee-metrics/src/main/scala/com/oracle/infy/wookiee/component/metrics/monitoring/MonitoringSettings.scala
> +    Try(Option(config.getStringList("graphite.disabled-metric-attributes").asScala.toList)).getOrElse(None)
_config.getStringList("graphite.disabled-metric-attributes").asScala.toSet_ gives out an empty set when the key does not exist or it has an empty list as value, so I have removed Option/Try.

2022-09-01 16:04 UTC, Kraagen approved these changes

2022-09-02 18:28 UTC, malibuworkcrew approved these changes

2022-09-02 18:28 UTC, merged